apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-direct-pv
spec:
  storageClassName: nfs-direct
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/cube-pool/k8s-nfs/nfs-direct
    server: 10.0.0.26
