apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nfs-demo-map-folder
  name: map-folder-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
