apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-direct-site
  namespace: nfs-demo-nfs-direct
  name: nfs-direct-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-direct-site
  template:
    metadata:
      labels:
        app: nfs-direct-site
    spec:
      volumes:
        - name: nfs-direct-nfs
          persistentVolumeClaim:
            claimName: nfs-direct-pvc
      containers:
        - image: nginx
          name: nfs-direct-site
          volumeMounts:
            - name: nfs-direct-nfs
              mountPath: /usr/share/nginx/html
