apiVersion: v1
kind: Service
metadata:
  name: nfs-direct-service
  namespace: nfs-demo-nfs-direct
spec:
  type: NodePort
  selector:
    app: nfs-direct-site
  ports:
    - name: http
      port: 80
      nodePort: 30200
      targetPort: 80
      protocol: TCP
