apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-1
  namespace: nfs-demo-storage-class
spec:
  storageClassName: nfs-lab-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
