kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: nfs-storage-class-site
  namespace: nfs-demo-storage-class
  name: nfs-storage-class-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-storage-class-site
  template:
    metadata:
      labels:
        app: nfs-storage-class-site
    spec:
      volumes:
        - name: nfs-storage-class-volume
          persistentVolumeClaim:
            claimName: nfs-pvc-1
      containers:
        - image: nginx
          name: nfs-storage-class-site
          volumeMounts:
            - name: nfs-storage-class-volume
              mountPath: /usr/share/nginx/html
