apiVersion: v1
kind: Service
metadata:
  name: nfs-storage-class-service
  namespace: nfs-demo-storage-class
spec:
  type: NodePort
  selector:
    app: nfs-storage-class-site
  ports:
    - name: http
      port: 80
      nodePort: 30300
      targetPort: 80
      protocol: TCP
