apiVersion: v1
kind: PersistentVolume
metadata:
  name: map-folder-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/var/nfs/host-mapped'
