apiVersion: v1
kind: Service
metadata:
  name: map-folder-service
  namespace: nfs-demo-map-folder
spec:
  type: NodePort
  selector:
    app: map-folder-site
  ports:
    - name: http
      port: 80
      nodePort: 30100
      targetPort: 80
      protocol: TCP
